### ISSUE TITLE
Deployment failedon KC 10.0.2 standalone.xml

### ISSUE THREAD

**Issue by valsaraj** [zonaut/keycloak-extensions#4]
This error comes during deployment:
FATAL [org.keycloak.services] (ServerService Thread Pool -- 69) java.lang.NoClassDefFoundError: org/keycloak/theme/FreeMarkerUtil

**Comment by zonaut** [comment]
Can you provide more information about the problem you are experiencing?
The examples showing here are tested again Keycloak 11.0.0 so make sure your keycloak version is represented in the pom.xml of the spi you are trying to use.
The demo in this project has certain modules enabled by default for showing that they work together, if you don't use all modules make sure you change or revert changes made for these modules. You can find all the configuration changes made in each readme file.
For example, if you don't use the mail-template-override example you need to revert the changes made that are described in https://github.com/zonaut/keycloak-extensions/blob/master/spi-mail-template-override/README.md

**Comment by valsaraj** [comment]
I am using only spi-mail-template-override. Set the KC version as 10.0.2 which I am using and Java version as 1.8. Then build this module and deployed.

<maven.compiler.source>1.8</maven.compiler.source>
<maven.compiler.target>1.8</maven.compiler.target>
<keycloak.version>10.0.2</keycloak.version>

These are the only changes to module pom file and then run maven install for this project.
Modified standalone.xml as in readme file.

**Comment by zonaut** [comment]
Have you made the needed changes in your standalone-ha.xml file?
The readme for the spi-mail-template-override states that you need to make some changes to the default Keylcoak config as you can read in https://github.com/zonaut/keycloak-extensions/blob/master/spi-mail-template-override/README.md

Add the following in your standalone-ha.xml, it's possible you need to make these changes in standalone.xml depending if you use docker or the default bin package you downloaded.

```
<subsystem xmlns="urn:jboss:domain:ee:5.0">
    ...
    <global-modules>
        <module name="org.freemarker"/>
    </global-modules>
    ...
</subsystem>
```
Also add the following to disable the default email template provider

```
<subsystem xmlns="urn:jboss:domain:keycloak-server:1.1">
    <web-context>auth</web-context>
    ...
    <spi name="emailTemplate">
        <provider name="freemarker" enabled="false"/>
    </spi>
    ...
</subsystem>
```

**Comment by valsaraj** [comment]
I applied these already in standalone.xml.

<subsystem xmlns="urn:jboss:domain:ee:5.0">
            <global-modules>
                <module name="org.freemarker"/>
            </global-modules>
...
<spi name="emailTemplate">
                <provider name="freemarker" enabled="false"/>
            </spi>

spi-event-listener example worked fine but this one having this issue.

**Comment by zonaut** [comment]
I've just tested it without the other modules and I found the problem.
You also need to add `<module name="org.keycloak.keycloak-services"/>` to the global-modules
i will update the readme files.
Can you try it out and let me know if you got it working.

**Comment by valsaraj** [comment]
Using jboss-deployment descriptor we don't need global modules. I checked both and are working fine.

Thank you!

**Comment by zonaut** [comment]
I've fixed all the jboss-deployment descriptors in my examples, they where present but they where in the wrong directory.
I've also removed the global-modules section in the standalone-ha.xml file.

Thanks for giving me pauze again on this matter and give it a second look.
