### ISSUE TITLE
SPI Provider with third-party library

### ISSUE THREAD

**Issue by jachinte** [zonaut/keycloak-extensions#5]
Hello,

I've been trying to add Apache Commons Configuration to `spi-events-listener`, but I keep getting `ClassNotFoundException`. I've tried many many many things I found online but so far none has worked. This seems to be a common pain point, based on the many questions/posts I read about this topic. Would you please consider updating the `spi-events-listener` project to include a third-party library? (e.g., Apache Commons Configuration).

I added three branches to my fork of this repository. I tried using Maven's shade plugin, creating a module and creating an EAR file. This is the first time I work with Jboss/Wildfly.

https://github.com/jachinte/keycloak-extensions

```
Caused by: java.lang.ClassNotFoundException: org.apache.commons.configuration2.PropertiesConfiguration from [Module "deployment.keycloak-server.war" from Service Module Loader]
keycloak    | 	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255)
keycloak    | 	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
keycloak    | 	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
keycloak    | 	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
keycloak    | 	at java.base/java.lang.Class.forName0(Native Method)
keycloak    | 	at java.base/java.lang.Class.forName(Class.java:398)
keycloak    | 	at deployment.spi-event-listener-ear-0.0.1-SNAPSHOT.ear.spi-event-listener-module.jar//org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:993)
keycloak    | 	at deployment.spi-event-listener-ear-0.0.1-SNAPSHOT.ear.spi-event-listener-module.jar//org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:1059)
keycloak    | 	at deployment.spi-event-listener-ear-0.0.1-SNAPSHOT.ear.spi-event-listener-module.jar//org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:1042)
keycloak    | 	at deployment.spi-event-listener-ear-0.0.1-SNAPSHOT.ear.spi-event-listener-module.jar//org.apache.commons.configuration2.beanutils.BeanHelper.loadClass(BeanHelper.java:508)
keycloak    | 	at deployment.spi-event-listener-ear-0.0.1-SNAPSHOT.ear.spi-event-listener-module.jar//org.apache.commons.configuration2.beanutils.BeanHelper.fetchBeanClass(BeanHelper.java:546)
keycloak    | 	... 99 more
```

Thank you,
Miguel

**Comment by EmilIfrim** [comment]
I have found something that seems kind of related (https://stackoverflow.com/questions/37181611/gradle-throws-classnotfoundexception-using-a-plugin-with-dependencies)

By analogy, my fix was:

`ClassLoader moduleClassLoader = Thread.currentThread().getContextClassLoader();
Thread.currentThread().setContextClassLoader(PropertiesConfiguration.class.getClassLoader());

//add here the code where apache configuration2 is used, that is where configuration is built

Thread.currentThread().setContextClassLoader(moduleClassLoader);`

I hope it works for you.

**Comment by jachinte** [comment]
@EmilIfrim thank you so much! It worked for me too. I updated the EAR branch in case anyone is interested.
